version: "3"

services:

  elasticsearch:
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
    image: 192.168.124.8:2019/elasticsearch:6.8.5
    volumes:
      - /test/storage/elk/elasticsearch/data:/usr/share/elasticsearch/data
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 2G
      placement:
        constraints:
          - node.labels.type==test02
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: 192.168.124.8:2019/kibana:6.8.5
    environment:
      ELASTICSEARCH_URL: 192.168.124.8:9200
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 1G
    ports:
      - "5601:5601"
  logstash:
    image: 192.168.124.8:2019/logstash:6.8.5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - /test/conf/elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    command: ["logstash","-f","/usr/share/logstash/pipeline/logstash.conf"]

  filebeat:
    image: 192.168.124.8:2019/elastic/filebeat:6.8.5
    deploy:
      mode: global
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - /test/conf/elk/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /test/storage/logs:/usr/share/filebeat/logs


