version: '3.1'


services:

  redis-sentinel:
    image: redis-sentinel:${TAG:-latest}
    environment:
      - REDIS_IP=redis-zero
      - REDIS_MASTER_NAME=redismaster
    deploy:
      replicas: 3
    networks:
      - redis
    ports:
      - "26379:26379"

  redis:
    image: redis-look:${TAG:-latest}
    environment:
      - REDIS_SENTINEL_IP=redis-sentinel
      - REDIS_MASTER_NAME=redismaster
      - REDIS_SENTINEL_PORT=26379
    deploy:
      replicas: 3
    networks:
      - redis
    ports:
      - "6379:6379"

networks:
  redis:
    external: true
